services:
  db:
    image: mysql:latest
    container_name: herramientas
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: herramientas
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql  # Asegúrate de que el volumen esté definido

volumes:
  db_data: {}  # Define el volumen aquí
